version: '2'
services:
  zookeeper:
    container_name: zookeeper-ssl
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka-ssl
    depends_on:
      - zookeeper
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-ssl:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jaas/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./jaas/producer_jaas.conf:/etc/kafka/producer_jaas.conf
      - ./jaas/consumer_jaas.conf:/etc/kafka/consumer_jaas.conf
